spring.application.name=smart-society-portal

spring.datasource.url=jdbc:mysql://G3VHK1Eb6Lz3Uf7.root:<PASSWORD>@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/smart_society_portal
spring.datasource.username=G3VHK1Eb6Lz3Uf7.root
spring.datasource.password=EneBW9ggfvosDs74

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.port=${PORT:8080}